version: 2

jobs:
    test:
        docker:
            - image: circleci/golang:latest
        steps:
            - checkout
            - run:
                name: Test
                command: 'go test -v -race -cover -coverprofile=cover.out ./...'
            - run: 
                name: Upload code coverage
                command: 'bash <(curl -s https://codecov.io/bash)'

workflows:
    version: 2
    test:
        jobs:
            - test
