name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get Go environment
      id: go-env
      run: |
        echo "::set-output name=cache::$(go env GOCACHE)"
        echo "::set-output name=modcache::$(go env GOMODCACHE)"

    - name: Set up Go cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.go-env.outputs.cache }}
          ${{ steps.go-env.outputs.modcache }}
        key: go-cache-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-cache-

    - name: Test
      run: go test -v ./...
